### PR TITLE
Add .bat to ceylon if running in a Windows environment.

### PR DESCRIPTION
**Pull request by ageery**
On Windows, I was getting an error about ceylon not being executable because the .bat ext wasn't specified.

### CODE REVIEW

**Comment by ageery** [comment]
Rather than passing no environment (an empty array -- []) when calling the ceylon command, call execute with null -- this has the effect of using the current environment.  Without this, I lose JAVA_HOME info and this interferes with ceylon's ability to find java.

**Comment by renatoathaydes** [comment]
This is great! Will test on Mac/Linux and merge as soon as possible.

**Comment by renatoathaydes** [comment]
Merged. Will release after I fix some more small issues. Thanks!

**Comment by ageery** [comment]
Awesome -- thanks for the great plugin!

Andrew

**Pull request merged**
